name: Kouta-internal megabuild and manual deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - hahtuva
          - untuva
          - pallero
          - sade
      image-tag:
        type: string
        description: image tag to use for deployment
  push:
    paths-ignore:
      - '**.md'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout read
  security-events: write # Required for trivy results

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'maven'

      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Helsinki"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: kouta-internal-build
          aws-region: eu-west-1

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build with Maven
        run: |
          cd postgresql/docker
          docker build --tag koutainternal-postgres .
          cd -
          mvn clean package -B

      - uses: actions/cache@v4
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

  push-container:
    needs: test-and-build
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: 'kouta-internal'
      base-image: 'utility/baseimage-fatjar-openjdk11:master'
      configfolder: 'src/main/resources/*'
      jarfile: 'kouta-internal-*-with-dependencies'
      type: jar
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

  deploy-to-environment:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.environment != 'none' }}
    needs: [test-and-build, push-container]
    uses: Opetushallitus/.github/.github/workflows/deploy-from-ecr-to-ecs.yml@main
    with:
      application: 'kouta-internal'
      environment: ${{ inputs.environment }}
      image-tag: ${{ inputs.image-tag }}